### ISSUE TITLE
Saving interactive view of the customized image (only) for others

### ISSUE THREAD

**Issue by jiyoungyoun** [knightjdr/prohits-viz-client#15]
I have combined two SAINT files to compare BioID profiles of the same bait expressed in two different cell types. One of the SAINT file contains multiple baits, so I have used customized image to visualize the two conditions of interest. 
In order to send this file to a collaborator, I would like to send the current view of customized image as the interactive view without sharing the entire dotplot from which this customized image was generated. 
Does this tool or function exist, where we can share just the customized view? When I download the interactive session file, I still see the entire dotplot session.

Of course, the users can get around this by re-running SAINT only with the baits to be compared (although there may be subtle changes since SAINT also accounts for the bait profiles that are used as input). Or the user can download the view and use other softwares (illustrator) to make a figure.

I think this will be useful, if other baits in the original analysis is unpublished work and the user would like to share the customized view quickly.

**Comment by knightjdr** [comment]
If you just want the customized image, click on the the save tab on the side panel and then you can save the image as an svg or png. It will save whatever image you are looking at, either the customized or main image.

If you want an interactive version of just the customized image you will have to rerun the analysis specifying the baits and preys to include with the no clustering option. But this is pretty trivial to do. If you already have the customized image made, click on the analysis tab on the side panel and you can grab the column (bait) and row (prey) names by right clicking on the appropriate menu.

Adding an option to export just the customized image as an interactive file would be very low on the priority list because of the existing alternatives.
